---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bds
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bds
  labels:
    app: bds
spec:
  replicas: 1
  template:
    metadata:
      name: bds
      labels:
        app: bds
    spec:
      containers:
        - name: bds
          image: itzg/minecraft-bedrock-server
          imagePullPolicy: Always
          env:
            - name: EULA
              value: "TRUE"
            - name: GAMEMODE
              value: survival
            - name: DIFFICULTY
              value: normal
          volumeMounts:
            - mountPath: /data
              name: data
          livenessProbe:
            exec:
              command: ["nc", "-zu", "127.0.0.1", "19132"]
            initialDelaySeconds: 30
            successThreshold: 1
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          startupProbe:
            exec:
              command: ["nc", "-zu", "127.0.0.1", "19132"]
            initialDelaySeconds: 30
            successThreshold: 1
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["nc", "-zu", "127.0.0.1", "19132"]
            initialDelaySeconds: 30
            successThreshold: 1
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bds
  selector:
    matchLabels:
      app: bds
---
apiVersion: v1
kind: Service
metadata:
  name: bds
spec:
  selector:
    app: bds
  ports:
    - port: 19132
      protocol: UDP
  type: LoadBalancer